### ISSUE TITLE
GEPRC F411 35A AIO softserial (T11 R11 pin)

### ISSUE THREAD

**Issue by Alexx2321979** [emuflight/EmuFlight#945]
**Describe the bug**
pin T11 R11 not work softserial gps
**To Reproduce**
what i need doo this trabl?
**Expected behavior**
softserial this pin work whis gps module
**Flight controller configuration**
Create a `diff` and post it here in a code block. Put ``` (three backticks) at the start and end of the `diff` block (instructions  on how to do a diff: https://oscarliang.com/use-diff-not-dump-betaflight/)

**Setup / Versions**
 - Flight controller [what type is it, where was it bought from];
 - Other components [RX, VTX, brand / model for all of them, firmware version where applicable];
 - how are the different components wired up.
GEPRC F411 35A AIO in drone geprc rocket lite.
**Additional context**
please help

**Comment by nerdCopter** [comment]
EmuFlight is based from ButterFlight/Betaflight 3.5.x . EmuF GPS support is severely lacking and I do not know much about GPS configuration.

GEPRCF411_AIO definition seems to already support softserial: https://github.com/emuflight/EmuFlight/blob/731894ae28f701601a044effc1cd3bdd314e2da3/src/main/target/GEPRCF411_AIO/target.h#L87-L105
I'm wondering if UART1 and SOFTSERIAL1 cannot be used at same time due to identical PINs PA0 & PB10. I do not know enough about it.
Only these Baro/Mag are supported if it's any consolation: https://github.com/emuflight/EmuFlight/blob/731894ae28f701601a044effc1cd3bdd314e2da3/src/main/target/GEPRCF411_AIO/target.mk#L9-L13

**Comment by Alexx2321979** [comment]
![20231102_185006](https://github.com/emuflight/EmuFlight/assets/123832699/9149fc8c-3d89-41b7-b95e-f11fefef54b0)
![Screenshot_20231102_204116_Telegram](https://github.com/emuflight/EmuFlight/assets/123832699/2034e80b-283f-4be5-9903-765702c02cfd)

this stock firmware. R11 T11 is softserial? i konect GPS bn180, but not work.

**Comment by nerdCopter** [comment]
i would agree that 11 is softSerial. In Betaflight if you flashed 4.4 or later, you must enable GPS in cloud-build.
BetaFlight discord: https://discord.betaflight.com/
EmuFlight discord: https://discord.gg/BWqgBg3

**Comment by Alexx2321979** [comment]
> you must enable GPS in cloud-build.

sorry, please give more info for this.
i have Betaflight 4.4.2 nevest, gps enable in konfiguration - UBLOX potr auto, but not work....

**Comment by nerdCopter** [comment]
if you have an M10 GPS, betaflight 4.5 has support for M10.
Please go to appropriate Discord server for help and support.

**Comment by Alexx2321979** [comment]
411 chip not work normal in softserial! 
Sbus work through uart1 and conflicts with another device on uart 1. softserial also conflicts with a device on uart 2. the output is simple 411 complete......
tested on both geprc f411aio and jhemcu f411 noxe v3
It is impossible to install 3 devices (vtx hd, cross, gps) only 2 devices. It's better to buy a board with a 405 chip

**Comment by nerdCopter** [comment]
Thank you for the information.
F411 known to be less than ideal, but i did not know these details.

F411 also sometimes needs pid_denom = 2 to process all the filters and features. (https://github.com/emuflight/EmuFlight/issues/915)
